name: release version

on:
  push:
    branches:
      - master
      - feature-ehcache


jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        uses: guillonapa/action-maven-cli/jdk8@master
        with:
          lifecycle: 'clean package test'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        run: |
          docker build --push --platform linux/amd64,linux/arm64,linux/arm/v7 -t reluxa/s3proxy:poc_v2 . # will run buildx